Fix subproject build
Use add_project_arguments instead of add_global_arguments

Fixes:
ERROR: Function 'add_global_arguments' cannot be used in subprojects because there is no way to make that reliable.

Also restore strcasecmp.c

Fixes:
ERROR: File strcasecmp.c does not exist.